# Generated by Django 3.2.7 on 2021-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slp', models.FloatField(null=True)),
                ('Mode', models.CharField(choices=[('Win', 'Win'), ('lose', 'lose'), ('Adventure', 'Adventure'), ('DailyQuest', 'DailyQuest')], max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
